put:
  tags:
  - Admin
  summary: Grant permissions to role
  description: |
    Grant permissions to role
  security:
    - bearerAuth: []
  requestBody:
    description: Permissions
    content:
      application/json:
        schema:
          $ref: "../../../../../schemas/apis/admin/application/roles/grant-permissions/request/Request.yaml"
    required: true
  responses:
    200:
      description: Success
      content:
        text/plain:
          schema:
            type: string
            example: Success
    400:
      description: Bad request
    401:
      description: Unauthorized
    500:
      description: Internal error