put:
  tags:
  - Admin
  summary: Grant account roles
  description: |
    Grant account roles

    **Auth:** Requires auth token with 'all_admin_core' permission
  security:
    - bearerAuth: []
  requestBody:
    description: Roles
    content:
      application/json:
        schema:
          $ref: "../../../../../schemas/apis/admin/application/account/roles/grant/request/Request.yaml"
    required: true
  responses:
    200:
      description: Success
      content:
        text/plain:
          schema:
            type: string
            example: Success
    400:
      description: Bad request
    401:
      description: Unauthorized
    500:
      description: Internal error