required:
  - app_id
  - version
  - data
type: object
properties:
  id:
    type: string
  app_id:
    type: string
  version:
    type: string
    description: conforms major.minor.patch format
  data:
    type: object