required:
  - app_type_id
  - app_org_id
  - version
  - data
type: object
properties:
  id:
    type: string
  app_type_id:
    type: string
  app_org_id:
    type: string
  version:
    type: string
    description: conforms major.minor.patch format
  data:
    type: object