type: object
properties:
  id:
    type: string
  application:
    $ref: "./Application.yaml"
  organization:
    $ref: "./Organization.yaml"
  services_ids:
    type: array
    items:
      type: string
  TODO:
    type: string