required:
  - id
  - name
  - app_id
type: object
properties:
  id:
    type: string
  name:
    type: string
  app_id:
    type: string
  permissions:
    type: array
    items:
      $ref: "./ApplicationPermission.yaml"
  roles:
    type: array
    items:
      $ref: "./ApplicationRole.yaml"