required:
  - id
  - name
type: object
properties:
  id:
    readOnly: true
    type: string
  name:
    type: string
  multi_tenant:
    type: boolean
  requires_own_users:
    type: boolean
  types:
    type: array
    items:
      $ref: "./ApplicationType.yaml"
  organizations:
    type: array
    items:
      $ref: "./ApplicationOrganization.yaml"