required:
  - id
  - name
type: object
properties:
  id:
    type: string
  name:
    type: string
  application:
    $ref: "./Application.yaml"
  permissions:
    type: array
    items:
      $ref: "./ApplicationPermission.yaml"
  roles:
    type: array
    items:
      $ref: "./ApplicationRole.yaml"