post:
  tags:
  - System
  summary: Create application type version
  description: |
    Create application type version
  security:
    - bearerAuth: []
  parameters:
  - name: id
    in: path
    description: ID of the application
    required: true
    style: simple
    explode: false
    schema:
      type: string
  requestBody:
    description: Creates application type version
    content:
      application/json:
        schema:
          $ref: "../../schemas/apis/system/create-application-type-version/request/Request.yaml"
    required: true
  responses:
    200:
      description: Success
      content:
        text/plain:
          schema:
            $ref: "../../schemas/apis/system/create-application-type-version/response/Response.yaml"
    400:
      description: Bad request
    401:
      description: Unauthorized
    500:
      description: Internal error