get:
  deprecated: true
  tags:
  - System
  summary: Reads mobile app configuration by given id
  description: |
    **Auth:** Requires user auth token
  security:
    - bearerAuth: []
  parameters:
    - name: id
      in: path
      description: app config id to read
      required: true
      style: simple
      explode: false
      schema:
        type: string
  responses:
    200:
      description: successfully read mobile app configuration
      content:
        application/json:
          schema:
            $ref: "../../schemas/apis/system/appconfigs/response/Response.yaml"
    400:
      description: Bad request.
    401:
      description: Unauthorized
    404:
      description: AppConfig not found
    500:
      description: Internal error
put:
  deprecated: true
  tags:
  - System
  summary: Updates mobile app configuration
  description: |
    **Auth:** Requires user auth token
  security:
    - bearerAuth: []
  parameters:
  - name: id
    in: path
    description: app config id to update
    required: true
    style: simple
    explode: false
    schema:
      type: string
  requestBody:
    description: update AppConfig object
    content:
      application/json:
        schema:
          $ref: "../../schemas/apis/system/appconfigs/request/Request.yaml"
    required: true
  responses:
    200:
      description: successfully updated mobile app configuration
      content:
        text/plain:
          schema:
            type: string
            example: Success
    400:
      description: Bad request
    401:
      description: Unauthorized
    405:
      description: Invalid input
    500:
      description: Internal error
delete:
  deprecated: true
  tags:
  - System
  summary: Deletes mobile app configuration
  description: |
     **Auth:** Requires user auth token
  security:
    - bearerAuth: []
  parameters:
  - name: id
    in: path
    description: app config id to delete
    required: true
    style: simple
    explode: false
    schema:
      type: string
  responses:
    200:
      description: AppConfig deleted
    400:
      description: Bad request
    401:
      description: Unauthorized
    404:
      description: AppConfig not found
    500:
      description: Internal error