delete:
  tags:
  - System
  summary: Delete version
  description: |
    Deletes an existing application type version registration record
  security:
    - bearerAuth: []
  parameters:
    - name: appliction-type-id
      in: path
      description: The app type ID of the registration to delete
      required: true
      schema:
        type: string
    - name: version-id
      in: path
      description: The version ID of the registration to delete
      required: true
      schema:
        type: string
  responses:
    200:
      description: Success
      content:
        text/plain:
          schema:
            type: string
            example: Success
    400:
      description: Bad request
    401:
      description: Unauthorized
    500:
      description: Internal error
