get:
  deprecated: true
  tags:
  - Admin
  summary: Get applications for an organizations
  description: |
    Gets applications for an organizations
  security:
    - bearerAuth: []
  responses:
      200:
        description: Successful operation
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "../../../schemas/apis/admin/get-applications/response/Response.yaml"
      400:
        description: Bad request
      401:
        description: Unauthorized
      500:
        description: Internal error