put:
  tags:
  - Admin
  summary: Update applications
  description: |
    Updates applications
  parameters:
  - name: id
    in: path
    description: ID of the application that needs to be updated
    required: true
    style: simple
    explode: false
    schema:
      type: string
  requestBody:
    description: update one application
    content:
      application/json:
        schema:
          $ref: "../../schemas/organization/Application.yaml"
    required: true
  responses:
    200:
      description: Success
      content:
        text/plain:
          schema:
            type: string
            example: Success
    400:
      description: Bad request
    401:
      description: Unauthorized
    500:
      description: Internal error
get:
  tags:
  - Admin
  summary: Get application
  description: |
    Gets application
  parameters:
  - name: id
    in: path
    description: ID of the application
    required: true
    style: simple
    explode: false
    schema:
      type: string
  responses:
    200:
      description: successful operation
      content:
        application/json:
            schema:
              $ref: "../../schemas/organization/Application.yaml"
    400:
      description: Bad request
    401:
      description: Unauthorized
    404:
      description: Not Found
    500:
      description: Internal error
delete:
  tags:
  - Admin
  summary: Delete application
  description: |
    Delete application
  parameters:
   - name: id
     in: path
     description: ID of the application that needs to be deleted
     required: true
     style: simple
     explode: false
     schema:
       type: string
  responses:
      200:
        description: Successful operation
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "../../schemas/organization/Application.yaml"
      400:
        description: Bad request
      401:
        description: Unauthorized
      500:
        description: Internal error