post:
  tags:
  - Services
  summary: Gets app config
  description: |
    Returns the app config for the highest version that is equal to or less than the provided version

    **Auth:** Requires a valid API Key for access.
  requestBody:
    description: |
      App config query
    content:
      application/json:
        schema:
          $ref: "../../../schemas/apis/services/appconfigs/request/Request.yaml"
  responses:
    200:
      description: successfully read app configuration
      content:
        application/json:
          schema:
            $ref: "../../../schemas/application/AppConfig.yaml"
    400:
      description: Bad request.
    401:
      description: Unauthorized
    404:
      description: AppConfig not found
    500:
      description: Internal error