get:
  tags:
  - Services
  summary: Reads mobile app configuration
  description: |
    Auth: Requires a valid API Key for access.
  parameters:
    - name: version
      in: query
      description: query by mobile app version and app_id, results contain all app configurations if no paramer is given; If given version and app_id, it will return the closest app config that is less than or equal to the given version.
      style: form
      explode: false
      schema:
        type: string
    - name: app_id
      in: query
      description: query by mobile app version and app_id, results contain all app configurations if no app_id is given; If given app_id, it will return the app configs that match the given app_id.
      style: form
      explode: false
      schema:
        type: string
  responses:
    200:
      description: successfully read mobile app configuration
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "../../../schemas/apis/services/appconfigs/response/Response.yaml"
    400:
      description: Bad request.
    401:
      description: Unauthorized
    404:
      description: AppConfig not found
    500:
      description: Internal error