get:
  tags:
  - Services
  summary: Reads app configuration
  description: |
    Auth: Requires a valid API Key for access.
    If version is provided, the app config for the highest version that is equal to or less than this value will be returned as the only item in the list.
    Otherwise it will return a list of all app config versions for the given app_id.
  parameters:
    - name: app_id
      in: query
      description: query by app version and app_id, results contain all app configs that match the given app_id.
      required: true
      style: form
      explode: false
      schema:
        type: string
    - name: version
      in: query
      description: query by app version and app_id. If given version and app_id, it will return the closest app config that is less than or equal to the given version.
      style: form
      explode: false
      schema:
        type: string
  responses:
    200:
      description: successfully read app configuration
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "../../../schemas/apis/services/appconfigs/response/Response.yaml"
    400:
      description: Bad request.
    401:
      description: Unauthorized
    404:
      description: AppConfig not found
    500:
      description: Internal error